spring:
  datasource-transform:
    url: jdbc:postgresql://${AQTS_DATABASE_ADDRESS}:${AQTS_DATABASE_PORT}/${AQTS_DATABASE_NAME}?currentSchema=${AQTS_SCHEMA_NAME}
    username: ${AQTS_SCHEMA_OWNER_USERNAME}
    password: ${AQTS_SCHEMA_OWNER_PASSWORD}
    hikari:
      maximum-pool-size: 2
  datasource-observation:
    url: jdbc:postgresql://${OBSERVATION_DATABASE_ADDRESS}:${OBSERVATION_DATABASE_PORT}/${OBSERVATION_DATABASE_NAME}?currentSchema=${OBSERVATION_SCHEMA_NAME}
    username: ${OBSERVATION_SCHEMA_OWNER_USERNAME}
    password: ${OBSERVATION_SCHEMA_OWNER_PASSWORD}
    hikari:
      maximum-pool-size: 2

logging:
  level:
    org.postgresql: DEBUG
    com.zaxxer: OFF
